name: 'lstm_ed'
feature_size: 5
hidden_size: 20
#encoder_feedforward_size:
#decoder_feedforward_size:
#latent_length:
#latent_number:
encoder_layer_number: 1
decoder_layer_number: 1
#encoder_head_number:
#decoder_head_number:
encoder_dropout: 0.1
decoder_dropout: 0.1
encoder_use_bias: 'true'
decoder_use_bias: 'true'
epoch_number: 40
test_ckpts_number: 40
batch_size: 32
window_size: 30
train_gaussian_percentage: 0.2
learning_rate: 1e-3
#learning_rate_decay:
#start_decay_steps:
#decay_steps:
#decay_method:
#warmup_steps:
gpu: 0
#early_stopping:
output_dir: 'reports/experiments/lstm_ed'
tensorboard_dir: 'reports/experiments/lstm_ed/runs'
save_every_epoch: 1
